name: b3dx
favicon: null
layout_spectrum: 0.21284
typography_spectrum: 0.49715
title: b3dx
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: UA-72191177-1
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#696363'
    - '#322b61'
    - '#fd8374'
    - '#b91e12'
  brandStrength: 0.5
  lightness: 0.8353518026415259
  saturation: 0.31435651634819806
  rhythmicContrast: 0.2831095680594444
purpose: []
